export const restaurantConstants = {
  SET_SELECTED_CUISINE: "SET_SELECTED_CUISINE",
  SET_SELECTED_RESTAURANT: "SET_SELECTED_RESTAURANT",
  SET_SHOW_ADD_REVIEW_MODAL: "SET_SHOW_ADD_REVIEW_MODAL",
  ADD_REVIEW: "ADD_REVIEW"
};
